### ISSUE TITLE
Ui Base Class 작업

### ISSUE THREAD

**Issue by sjjeong** [mash-up-kr/9tique-android#33]
Ui Base Class 작업

1. DataBinding
2. Add/Replace Fragment
3. Show Toast/SnackBar

**Comment by opklnm102** [comment]
해당 이슈에서 어떤걸 할껀지 좀더 구체적으로 디스크립션을 작성할 필요가 있을듯
제목도 뭘 위한 기초작업인지 명확하게 해야 나중에 이해하기 빠를듯
해당 이슈뿐만 아니라 다른 이슈에도 적용해주세요

**Comment by omjoonkim** [comment]
DataBinding!

**Comment by opklnm102** [comment]
@omjoonkim 시간되면 우리꺼 코드리뷰좀 해줘요

**Comment by omjoonkim** [comment]
언제나 보고있땁니당
