### ISSUE TITLE
설정 화면 개발

### ISSUE THREAD

**Issue by opklnm102** [mash-up-kr/9tique-android#5]
## 설정 화면 개발

_**와이어프레임 Page18~19 참고**_

**Comment by opklnm102** [comment]
@dbsl0145 뷰타입을 다르게하면 리스트에서 다른 모양의 아이템을 보여줄 수 있어요

**Comment by chaeniiz** [comment]
@opklnm102 어떤 타입으로 바꿔야 하나요...?!

**Comment by opklnm102** [comment]
@dbsl0145 [Heterogenous Layouts inside RecyclerView](https://guides.codepath.com/android/Heterogenous-Layouts-inside-RecyclerView) 여기 참고해서 해보세요
