### ISSUE TITLE
프로모션 상품 리스트 화면 기능 개발

### ISSUE THREAD

**Issue by sjjeong** [mash-up-kr/9tique-android#64]
1. 프로모션 상품 리스트 가져와서 보여주기
2. 상품 상세화면으로 이동
3. 카테고리별 분류하기
4. 최신순, 인기순, 낮은가격순, 높은가격순으로 정렬하기

**Comment by opklnm102** [comment]
해당 이슈는 #31 에서 진행도록 하고, close하도록 하겠음
